// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  two_col_media: dynamic(() => import("./TwoColMedia")),
  video_embed: dynamic(() => import("./VideoEmbed")),
};
